kconfig: remove unused function `GC_AXIS_BUTTON_NEG`
This was originally added in `joy.h`, and was moved to `kconfig.cpp` in
commit e1db42e81cdcb632e3e58f1ae4a911e324983ebd.  `GC_AXIS_BUTTON` is
used in `kconfig.cpp`, but `GC_AXIS_BUTTON_NEG` is never called
anywhere.  Its only use was in a comment.  gcc allows an unused
`constexpr` function in the anonymous namespace of the main translation
unit.  x86_64-pc-linux-gnu clang-21 also accepts this without a warning.
OS X clang ("Apple clang version 17.0.0 (clang-1700.6.3.2)") warns for
this, and then the build fails:

```
similar/main/kconfig.cpp:123:20: error: unused function 'GC_AXIS_BUTTON_NEG' [-Werror,-Wunused-function]
  123 | constexpr unsigned GC_AXIS_BUTTON_NEG(unsigned axis_id) { return SDL_CONTROLLER_BUTTON_MAX + (axis_id * 2) + 1; }
      |                    ^~~~~~~~~~~~~~~~~~
1 error generated.
```

Remove the unused function to fix the OS X clang build <https://github.com/dxx-rebirth/dxx-rebirth/actions/runs/26007079764/job/76440399285>.

Fixes: e1db42e81cdcb632e3e58f1ae4a911e324983ebd ("kconfig: move `GC_AXIS_BUTTON` to kconfig.cpp")